### ISSUE TITLE
numan folders language

### ISSUE THREAD

**Issue by ragadeeshu** [datateknik-lth/datateknik-lth#11]
Inser att jag själv är skyldig till hälften av dem, men jag följde standarden som var i den mappen utan att titta närmare på readme:n. Öppnar denna för att dubbelkolla att det är svenska det ska vara?

La även märke till att vissa kurser både har sammanfattningar och Sammanfattningar.

**Comment by ErikBjare** [comment]
Detta är fixat i #22
