### ISSUE TITLE
Two factor authentication for admin access

### ISSUE THREAD

**Issue by felixmulder** [datateknik-lth/datateknik-lth#23]
Hi all,

To ensure that the repository isn't compromised, the users with write access need to have two factor authentication enabled. Do this and notify us somehow (i.e. post in the issue or send us an email) and you will regain admin privileges.

Felix

**Comment by felixmulder** [comment]
cc @antoneliasson @ekroth @Jullekungfu @Kalas90

**Comment by ErikBjare** [comment]
Actually, I made it so that all users have push access, but only users with 2FA are in the `Owner` (admin) team of the organization. I see this is reflected in title, but not in OP so just wanted to clarify.

**Comment by felixmulder** [comment]
Yep, was tired this morning, hence the two edits :+1:
