### ISSUE TITLE
Statisk sida på github pages

### ISSUE THREAD

**Issue by Dracyr** [datateknik-lth/datateknik-lth#28]
Såg issue #5 och blev lite inspirerad till att göra en statisk sida, samt skriver en issue för att man inte kan göra pull requests för nya branches.

Använde middleman för att generera sidan, kod för det och lite mer info ligger i [min fork](https://github.com/Dracyr/datateknik-lth/tree/middleman). Själva sidan som genereras ligger på [http://dracyr.github.io/datateknik-lth/](http://dracyr.github.io/datateknik-lth/) för tillfället. 

Markdownen parsas med MathJax så att vanlig LaTeX formatering för matte funkar.

**Comment by felixmulder** [comment]
Låter som en bra lösning, har du lust visa något exempel på fungerande formatering i någon md, länka från README.md till sidan och göra en PR?

Såg att ifall man klickar sig uppåt i fil-hierarkin så hamnar man fel i.e. klicka på "ETS052-datakom" när du är i mappen så blir det 404.

Meaning, ifall du är här: https://dracyr.github.io/datateknik-lth/courses/ETS052-datakom/
och klickar dig uppåt så kommer du till https://dracyr.github.io/courses/ETS052-datakom som inte finns.

**Comment by Dracyr** [comment]
Fixade länkproblemet.

Indexsidan drar sin text direkt från masters readme.md, annars ligger det några i EIT060 vet jag.
Men matteformateringen fungerar inte för tillfället för MathJax cdn ligger nere verkar det som, får lägga in de js filerna i projektet sen istället när man kan få tag på dem igen.

Problemet är att jag inte kan göra en pull-request eftersom branchen inte finns i original repot, man kan bara göra PR mellan branches som finns. Kan ni med push access göra orphan branches för middleman och gh-pages kan jag göra pull-requests mot dem.

**Comment by antoneliasson** [comment]
Det gick inte att pusha orphan-branches (vilket är logiskt eftersom de inte finns). Men jag har pushat nuvarande tillståndet av dina två branches till datateknik-lth nu. Behöver vi också ett repo som heter datateknik-lth.github.io enligt punkt 1 på https://pages.github.com/ ?

**Comment by Dracyr** [comment]
Nope, github fixar själv pages. Ligger [uppe](http://datateknik-lth.github.io/datateknik-lth/) nu

**Comment by antoneliasson** [comment]
Bra. Besöker man https://datateknik-lth.github.io/ får man dock 404. Och jag får mail om build failure från Github på grund av git-annex symlänkar i /EDA230-optcomp/lectures/ . Får googla lite senare ikväll. Men kul att det funkar!

**Comment by Dracyr** [comment]
Aha, jo för att det ska komma upp på den länken får det ligga i ett datateknik-lth.github.io repo istället/också.

Hmm, ja, hade ju varit trevligt om de också hade kunnat länka direkt till sina filer.

**Comment by velixo** [comment]
Ursäkta, men förstår inte riktigt hur detta skulle påverka markdown-ekvationer problemet? :P

**Comment by Dracyr** [comment]
[MathJax](https://www.mathjax.org/) parsar och formaterar ekvationerna på sidan, så man behöver bara skriva dem med samma vanliga LaTeX syntax i markdownen så fungerar det.

**Comment by velixo** [comment]
Ah, gött. Kommer ekvationerna stå i LaTeX-syntax i markdown-filerna efter pandoc-konverting?

**Comment by Zolomon** [comment]
Ni kan använda https://github.com/Khan/KaTeX i stället. Det är lite snabbare än MathJax om jag minns rätt.

**Comment by felixmulder** [comment]
Jag tror det bästa blir att utvärdera detta i gh-pages branchen som nämnt i #29 .
