### ISSUE TITLE
Convert tex documents to markdown in gh-pages branch

### ISSUE THREAD

**Issue by felixmulder** [datateknik-lth/datateknik-lth#29]
Easy peasy, kör följande kommando på alla filer:

```bash
$ pandoc -f latex -t markdown file.tex > file.md
```
Detta borde göra att @Dracyr  s statiska sidor renderar innehållet vackert.

*EDIT:* För att förtydliga så ska filerna alltså pushas till master.

När detta är klart så planerar vi på att rensa historiken, möjligen kommer vi spara en legacy branch.

**Comment by felixmulder** [comment]
Som @Zolomon sa så kankse MathJax är långsamt och kan isf bytas ut mot https://github.com/Khan/KaTeX 

Men det är inget vi ska lägga tid på ifall MathJax visar sig tillräckligt snabbt.

**Comment by antoneliasson** [comment]
Varför rensa historiken? En färsk clone av repot tar 17 sekunder från Github och är 108 MB stor. Visst är commitmeddelandena av varierande kvalitet, men det har väl ingen dött av. Det visar bara att vi jobbat på detta länge.

**Comment by velixo** [comment]
Man kan lika gärna köra detta via ett python-script:
[Hämta alla filer på en viss file extension](http://stackoverflow.com/questions/3964681/find-all-files-in-directory-with-extension-txt-with-python)

Filnamnet kan man hämta med `file.name`

[Köra unix/linux kommand med python](http://www.cyberciti.biz/faq/python-execute-unix-linux-command-examples/)

**Comment by velixo** [comment]
Rättade scriptet, genererade md filerna och la upp allt i en [pull request](https://github.com/datateknik-lth/datateknik-lth/pull/30), då många av filerna var av tvivelaktig kvalite, med renderingsfel, konstig formattering o.s.v.

Nån med mer koll på hur repot borde se ut får gärna ta en titt och bestämma om dom vill mergea det eller inte :)

**Comment by ErikBjare** [comment]
Tycker verkligen inte att historiken bör raderas @felixmulder. Håller med @antoneliasson. 100MB är inte så farligt och med hemsidan @Dracyr fixade bör det minska behovet av clones drastiskt ändå.

Angående Python script @velixo så är de ju alltid trevliga men det görs lättare med en oneliner sh:

    find . -name '*.tex' -exec bash -c 'pandoc -f latex -t markdown "$0" > "${0/.tex/.md}"' {} \;

Har inte testat det ordentligt med tror det ska fungera.

**Comment by velixo** [comment]
Ah nice. Kan ju byta ut skriptet jag la in om den funkar bättre! Annars borde alla filer vara genererade och vara redo att commitas i [denna](https://github.com/datateknik-lth/datateknik-lth/pull/30). Filerna som genererades blev lite weird, ska jag pusha in dom och låta folk fixa dom i efterhand eller fixa det innan push?

**Comment by felixmulder** [comment]
Repot består av 113MB i vår `.git` dir -  98MB är faktiska filer (Totalt 211MB alltså). Historiken är onödigt stor, och inget vi behöver vara sentimentala över. Jag köper inte argumentet "det visar att vi har gjort något".

Den statiska sidan drar definitivt ner antal clones. Förhoppningsvis behöver ingen göra dem på eduroam i framtiden.

Vi lägger historikfrågan på is tillsvidare.
