### ISSUE TITLE
Uppdatera middleman-siten

### ISSUE THREAD

**Issue by antoneliasson** [datateknik-lth/datateknik-lth#31]
Efter PR #30 behöver sidan uppdaterats. Jag provade, och det gick åt skogen. Middleman bygger bara index-sidorna och inga kurssidor. Återställde till tidigare tillstånd med en force-push till gh-pages. Någon som har bättre koll på hur detta verktyg fungerar och kan fixa? Eventuellt är inte git-submodulen rätt inställd här för `git submodule update --remote --merge` skriver inte ut någonting oavsett var jag kör det.

**Comment by felixmulder** [comment]
cc @Dracyr

**Comment by Dracyr** [comment]
Kollade upp det, om man inte redan har submodulen nere (som jag hade) behöver man initiera den genom att först köra
```
git submodule init
```
innan man uppdaterar submodulen.

Jag gjorde en ny deploy nu.
