### ISSUE TITLE
Borttagning av Avancerade algoritmer

### ISSUE THREAD

**Issue by felixmulder** [datateknik-lth/datateknik-lth#34]
Den korta versionen
--------------------------
Eva Tardos har bekräftat att svaren till avancerade algoritmer är upphovsrättsskyddade. Dessa kommer därför tas bort med historik.

Den långa versionen
--------------------------
I helgen fick jag ett mail av en högskoleanställd utanför LTH. Denna person påpekade att PDF-filerna för Avancerade Algoritmer i vårt repo är upphovsrättsskyddade. Eftersom vi inte kan se på något sätt att dessa är upphovsrättsskyddade (det finns inga indikationer i filerna eller i deras ursprung), så svarade jag att vi kommer behålla dem. Denna personen lämnade då en saklig diskussionsnivå och tonen i dennes mail upplevdes ovänlig. Jag avslutade då konversationen med att påpeka detta och att informera denne om att jag mailat till författaren, Eva Tardos.

Tardos bekräftade igår att dessa filer är upphovsrättsskyddade. Därför kommer de tas bort med historik.

Vad vi kan göra istället
-----------------------------
Ifall någon sitter på egengjorda svar till dessa frågor så tar vi glädjeligen emot dem.

**Comment by antoneliasson** [comment]
Fixat med en rebase. Som en bieffekt är nu historiken linjär utan merges för de senaste ~100 committarna.
