### ISSUE TITLE
move to organization + rename

### ISSUE THREAD

**Issue by felixmulder** [datateknik-lth/datateknik-lth#9]
Hej! Vi har beslotat att repot borde ligga på en organisation istället. Det naturliga blev att kalla organisotionen för "datateknik-lth." Repot bör såludes byta namn för att inte hata "datateknik-lth/datateknik-lth".

Förslag?

**Comment by ErikBjare** [comment]
Jag är emot att dela upp i årskurser, vart fjärde år (tror jag) överses programplanen av institutionen och vid den senaste ändringen som kommer börja gälla för de nya nollorna/ettorna HT2015 så är många av kurserna flyttade mellan årskurserna. Ett förslag som är framtidssäkert är att byta till en `KURSKOD-kursnamn` struktur.

**Comment by velixo** [comment]
'datateknik-lth/ak2/linsys-FMAF10' försvann under restruktureringen, hade ni kunnat lägga till den igen?

**Comment by antoneliasson** [comment]
Det gjorde Felix i c6bbc8d03698c650e7ed3a7aadb9a807165513c9

**Comment by velixo** [comment]
Såg det, gött! :)
